// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type McpServerElicitationRequestParams = { threadId: string, 
/**
 * Active Codex turn when the elicitation was observed, if available.
 *
 * This is nullable because MCP defines elicitation as a general
 * server-to-client request, not a turn- or tool-call-scoped primitive.
 */
turnId: string | null, serverName: string, message: string, };
