// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type McpServerElicitationRequestParams = { threadId: string, 
/**
 * Active Codex turn when this elicitation was observed, if app-server could correlate one.
 *
 * This is nullable because MCP models elicitation as a standalone server-to-client request
 * identified by the MCP server request id. It may be triggered during a turn, but turn
 * context is app-server correlation rather than part of the protocol identity of the
 * elicitation itself.
 */
turnId: string | null, serverName: string, 
/**
 * Human-readable prompt from the underlying MCP elicitation request.
 *
 * Core currently reduces the upstream RMCP `CreateElicitationRequestParams` to this message
 * string before it reaches app-server, so the v2 API cannot expose the full form/url request
 * shape yet.
 */
message: string, };
